DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO   INT           NOT NULL,
    NOMBRE   VARCHAR(50)   NOT NULL,
    APELLIDO VARCHAR(50)   NOT NULL,
    BANCO    INT           NOT NULL,
    SALDO    NUMERIC(7, 2) NOT NULL
);

INSERT INTO CLIENTES
VALUES (DEFAULT, 567, 'HOMERO', 'SIMPSON', 12, 3500),
       (DEFAULT, 859, 'BART', 'SIMPSON', 10, 3000);